### ISSUE TITLE
Google detecta errores

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#104]
https://www.google.com/webmasters/tools/mobile-friendly/?url=http%3A%2F%2Fnolotiro.org%2Fes%2Fad%2F31321%2Fcosas-amublar-casa&hl=es&utm_source=wmx&utm_campaign=wmx_mft

No ocurre en todos los anuncios. Debes mirar el webmastertools.

**Comment by franciscout** [comment]
Voy a ir probando para ver que es lo que hace que diga que no esta optimizado (las dos cosas que dicen se mantienen en otros anuncios, como [este](https://www.google.com/webmasters/tools/mobile-friendly/?url=nolotiro.org%2Fes%2Fad%2F196397%2Fdescalcificador-para-el-agua&hl=es&utm_source=wmx&utm_campaign=wmx_mft) y [este](https://www.google.com/webmasters/tools/mobile-friendly/?url=http%3A%2F%2Fnolotiro.org%2Fes%2Fad%2F196655%2Ftortuga-pequena&hl=es&utm_source=wmx&utm_campaign=wmx_mft) , pero esos dos si que dicen estar optimizados)

**Comment by andreslucena** [comment]
Si, hablan de esto: 

http://beta.nolotiro.org/es/ad/31321/cosas-para-amublar-una-casa

Y también de separar los botones y enlaces para que sea más facil hacer click. Habria qeu fijarse con otras paginas pero yo creo q se le puede subir la cantidad de em del texto del body en mobile y revisar margins y paddings en general.

**Comment by deivid-rodriguez** [comment]
The site is right now pretty well optimized for mobile, but we try to keep improving it. In the case of the particular error posted here, it's a very uncommon case (it only happens for long links which hardly anybody posts). As a matter of fact, the ad linked to by @andreslucena is the only case I've seen.

So I think it's better to manually edit the ad or ignore the overflow when this happens rather than adding probably not cross-browser supported css properties or custom js. So I'm closing this, feel free to reopen if you think otherwise!
